### ISSUE TITLE
Hide/Show Buttons

### ISSUE THREAD

**Issue by johntom** [andyshora/wallop-slider-angularjs#3]
First, Thanks for this terrific directive as I love the results. One question I have is how I can use the full css file that shows and hides the prev and next buttons on the image as demonstrated at http://pedroduarte.me/wallop-s.... While I can get this to work all my bs styled buttons no longer display. I've tinkered with the css and I'm at a loss of how to accomplish this. I've commented out css below as a workaround. I initially and mistakingly posted as a comment. 

TIA
John

The code below is a snip from the complete css file https://github.com/WallopSlide...

//////////// btn
// position: absolute; AND opacity: 0; Causes conflict with all other buttons. Works fine with wallop-slider directive.

//@media only screen and (min-width: 480px) {
// this causes conflict with buttons
//.btn {
// margin-top: 10px;
// position: absolute;
// z-index: 3;
// top: 50%;
// opacity: 0;
// -webkit-transition: opacity 200ms ease;
// -moz-transition: opacity 200ms ease;
// -ms-transition: opacity 200ms ease;
// transition: opacity 200ms ease;
//}

changed to
@media only screen and (min-width: 480px) {
.btn {
margin-top: 5px;
z-index: 3;
top: 50%;
-webkit-transition: opacity 200ms ease;
-moz-transition: opacity 200ms ease;
-ms-transition: opacity 200ms ease;
transition: opacity 200ms ease;
}

**Comment by andyshora** [comment]
Hi John,

I'm away from my Mac tonight. Have you tried changing the selector in the code you commented out to just target the wallop slider buttons? If you inspect them in the browser you can see the additional classes which are applied, or you can add a parent selector to ensure you target only them. That way you won't get the opacity:0 applied to all your buttons which are using the same .btn class. 

Andy

**Comment by johntom** [comment]
Hi Andy,

Thanks for reply! I will try your suggestions tonight or tomorrow and get back to you.

John

**Comment by johntom** [comment]
Hi Andy,

Brilliant! I've only used selectors for simple items and get intimidated with complex css rules and while I'm not sure if this is the optimum solution, it works.  Here's the mod's for you to check, comment and publish if desired.

Thanks

John

css

@media only screen and (min-width: 480px) {
    .btnwallop {

```
    margin-top: 5px;
    position: absolute;
    z-index: 3;
    top: 50%;
    opacity: 0;
    -webkit-transition: opacity 200ms ease;
    -moz-transition: opacity 200ms ease;
    -ms-transition: opacity 200ms ease;
    transition: opacity 200ms ease;
}
.wallop-slider:hover .btnwallop {
    opacity: .75;
}
.wallop-slider:hover .btnwallop:hover {
    opacity: 1;
}
```

}
.btnwallop:hover {
    cursor: pointer;
}
.btnwallop[disabled] {
    opacity: .4;
}
.btnwallop[wallopdisabled], .btnwallop[disabled]:hover {
    cursor: default;
}
@media only screen and (min-width: 480px) {
    .btnwallop[disabled] {
        visibility: hidden;
    }
}

@media only screen and (min-width: 480px) {
    .btnwallop--previous {
        left: 10px;
    }
}

@media only screen and (min-width: 480px) {
    .btnwallop--next {
        right: 10px;
    }
}

directive

.directive('wallopSlider', function () {
    return {
        template: '<div class="wallop-slider {{animationClass}}"><ul class="wallop-slider__list"><li class="wallop-slider__item {{itemClasses[$index]}}" ng-repeat="i in images"><img src="{{i}}"></li></ul><button ng-show="images.length>1" class="wallop-slider__btn wallop-slider__btnwallop--previous btnwallop btnwallop--previous " ng-disabled="prevDisabled" ng-click="onPrevButtonClicked()">Previous</button> <button ng-show="images.length>1" class="wallop-slider__btnwallop wallop-slider__btnwallop--next btnwallop btnwallop--next" ng-disabled="nextDisabled" ng-click="onNextButtonClicked()">Next</button></div>',
        restrict: 'EA',

**Comment by johntom** [comment]
Buttons now work as expected.
